// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCClkoHIXhoTrn0smlnCHSePXtGDjFyELg',
    appId: '1:147256949804:web:94ba31b39de0f98d8de589',
    messagingSenderId: '147256949804',
    projectId: 'paintshoploans',
    authDomain: 'paintshoploans.firebaseapp.com',
    storageBucket: 'paintshoploans.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcHOBN8v0uhfoePxKEJAR_vBTMfPRHjFI',
    appId: '1:147256949804:android:57bb5d6f1d38b8d38de589',
    messagingSenderId: '147256949804',
    projectId: 'paintshoploans',
    storageBucket: 'paintshoploans.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzOEa0S8-xoj3hfrpjXvjyFj4IsU9Xwqo',
    appId: '1:147256949804:ios:064cb92b744d8fb18de589',
    messagingSenderId: '147256949804',
    projectId: 'paintshoploans',
    storageBucket: 'paintshoploans.firebasestorage.app',
    iosBundleId: 'com.example.paintLoanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzOEa0S8-xoj3hfrpjXvjyFj4IsU9Xwqo',
    appId: '1:147256949804:ios:064cb92b744d8fb18de589',
    messagingSenderId: '147256949804',
    projectId: 'paintshoploans',
    storageBucket: 'paintshoploans.firebasestorage.app',
    iosBundleId: 'com.example.paintLoanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCClkoHIXhoTrn0smlnCHSePXtGDjFyELg',
    appId: '1:147256949804:web:808a11a560a8d8698de589',
    messagingSenderId: '147256949804',
    projectId: 'paintshoploans',
    authDomain: 'paintshoploans.firebaseapp.com',
    storageBucket: 'paintshoploans.firebasestorage.app',
  );
}
